# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ekz-tesla

before:
  hooks:
    - go mod tidy

builds:
  - id: ekz-tesla
    main: .
    binary: ekz-tesla
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/denysvitali/ekz-tesla/cmd/version.Version={{.Version}}
      - -X github.com/denysvitali/ekz-tesla/cmd/version.Commit={{.Commit}}
      - -X github.com/denysvitali/ekz-tesla/cmd/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE.txt

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/denysvitali/ekz-tesla:{{ .Tag }}-amd64"
      - "ghcr.io/denysvitali/ekz-tesla:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=EKZ Tesla charging station CLI"
      - "--label=org.opencontainers.image.url=https://github.com/denysvitali/ekz-tesla"
      - "--label=org.opencontainers.image.source=https://github.com/denysvitali/ekz-tesla"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    dockerfile: Dockerfile.goreleaser

  - image_templates:
      - "ghcr.io/denysvitali/ekz-tesla:{{ .Tag }}-arm64"
      - "ghcr.io/denysvitali/ekz-tesla:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=EKZ Tesla charging station CLI"
      - "--label=org.opencontainers.image.url=https://github.com/denysvitali/ekz-tesla"
      - "--label=org.opencontainers.image.source=https://github.com/denysvitali/ekz-tesla"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    dockerfile: Dockerfile.goreleaser

docker_manifests:
  - name_template: "ghcr.io/denysvitali/ekz-tesla:{{ .Tag }}"
    image_templates:
      - "ghcr.io/denysvitali/ekz-tesla:{{ .Tag }}-amd64"
      - "ghcr.io/denysvitali/ekz-tesla:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/denysvitali/ekz-tesla:latest"
    image_templates:
      - "ghcr.io/denysvitali/ekz-tesla:latest-amd64"
      - "ghcr.io/denysvitali/ekz-tesla:latest-arm64"

release:
  github:
    owner: denysvitali
    name: ekz-tesla
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## EKZ Tesla CLI {{ .Tag }}

    A command line tool to interact with EKZ charging stations.
  footer: |
    **Full Changelog**: https://github.com/denysvitali/ekz-tesla/compare/{{ .PreviousTag }}...{{ .Tag }}
