FROM alpine:latest AS certs
RUN apk --no-cache add ca-certificates tzdata

FROM scratch
COPY ekz-tesla /ekz-tesla
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=certs /usr/share/zoneinfo /usr/share/zoneinfo
ENTRYPOINT ["/ekz-tesla"]
